# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}]

# IP: bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mig_7series_0_0 || ORIG_REF_NAME==system_mig_7series_0_0}]

# IP: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0}]

# IP: bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_1 || ORIG_REF_NAME==system_dlmb_v10_1}]

# IP: bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_1 || ORIG_REF_NAME==system_ilmb_v10_1}]

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_1/system_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_1}]

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_1/system_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_1}]

# IP: bd/system/ip/system_lmb_bram_1/system_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_1 || ORIG_REF_NAME==system_lmb_bram_1}]

# IP: bd/system/ip/system_mdm_1_1/system_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mdm_1_1 || ORIG_REF_NAME==system_mdm_1_1}]

# IP: bd/system/ip/system_rst_mig_7series_0_83M_1/system_rst_mig_7series_0_83M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_mig_7series_0_83M_1 || ORIG_REF_NAME==system_rst_mig_7series_0_83M_1}]

# IP: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_0_0 || ORIG_REF_NAME==system_axi_quad_spi_0_0}]

# IP: bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_0_0 || ORIG_REF_NAME==system_axi_iic_0_0}]

# IP: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1}]

# IP: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0}]

# IP: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0}]

# IP: bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_0 || ORIG_REF_NAME==system_axi_gpio_3_0}]

# IP: bd/system/ip/system_axi_quad_spi_1_0/system_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_1_0 || ORIG_REF_NAME==system_axi_quad_spi_1_0}]

# IP: bd/system/ip/system_PmodACL_0_0/system_PmodACL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PmodACL_0_0 || ORIG_REF_NAME==system_PmodACL_0_0}]

# IP: bd/system/ip/system_PmodACL_0_0/src/PmodACL_pmod_bridge_0_0/PmodACL_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodACL_pmod_bridge_0_0 || ORIG_REF_NAME==PmodACL_pmod_bridge_0_0}]

# IP: bd/system/ip/system_PmodACL_0_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodACL_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodACL_axi_quad_spi_0_0}]

# IP: bd/system/ip/system_PmodACL_0_0/src/PmodACL_axi_gpio_0_0/PmodACL_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodACL_axi_gpio_0_0 || ORIG_REF_NAME==PmodACL_axi_gpio_0_0}]

# IP: bd/system/ip/system_PmodGPS_0_0/system_PmodGPS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PmodGPS_0_0 || ORIG_REF_NAME==system_PmodGPS_0_0}]

# IP: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_axi_uartlite_0_0/PmodGPS_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPS_axi_uartlite_0_0 || ORIG_REF_NAME==PmodGPS_axi_uartlite_0_0}]

# IP: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_pmod_bridge_0_0/PmodGPS_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPS_pmod_bridge_0_0}]

# IP: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodGPS_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPS_axi_gpio_0_0}]

# IP: bd/system/ip/system_PmodOLEDrgb_0_0/system_PmodOLEDrgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PmodOLEDrgb_0_0 || ORIG_REF_NAME==system_PmodOLEDrgb_0_0}]

# IP: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0}]

# IP: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1}]

# IP: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLEDrgb_pmod_bridge_0_0}]

# IP: bd/system/ip/system_PmodACL_1_0/system_PmodACL_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_PmodACL_1_0 || ORIG_REF_NAME==system_PmodACL_1_0}]

# IP: bd/system/ip/system_PmodACL_1_0/src/PmodACL_pmod_bridge_0_0/PmodACL_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodACL_pmod_bridge_0_0 || ORIG_REF_NAME==PmodACL_pmod_bridge_0_0}]

# IP: bd/system/ip/system_PmodACL_1_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodACL_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodACL_axi_quad_spi_0_0}]

# IP: bd/system/ip/system_PmodACL_1_0/src/PmodACL_axi_gpio_0_0/PmodACL_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodACL_axi_gpio_0_0 || ORIG_REF_NAME==PmodACL_axi_gpio_0_0}]

# IP: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0}]

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0}]

# IP: bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_intc_0_0 || ORIG_REF_NAME==system_axi_intc_0_0}]

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0}]

# IP: bd/system/ip/system_axi_mem_intercon_2/system_axi_mem_intercon_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_2 || ORIG_REF_NAME==system_axi_mem_intercon_2}]

# IP: bd/system/ip/system_xbar_5/system_xbar_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_5 || ORIG_REF_NAME==system_xbar_5}]

# IP: bd/system/ip/system_microblaze_0_axi_periph_3/system_microblaze_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_3 || ORIG_REF_NAME==system_microblaze_0_axi_periph_3}]

# IP: bd/system/ip/system_xbar_6/system_xbar_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_6 || ORIG_REF_NAME==system_xbar_6}]

# IP: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_0 || ORIG_REF_NAME==system_tier2_xbar_0_0}]

# IP: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_0 || ORIG_REF_NAME==system_tier2_xbar_1_0}]

# IP: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_0 || ORIG_REF_NAME==system_tier2_xbar_2_0}]

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}]

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0/user_design/constraints/system_mig_7series_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mig_7series_0_0 || ORIG_REF_NAME==system_mig_7series_0_0}]

# XDC: bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0/user_design/constraints/system_mig_7series_0_0_ooc.xdc

# XDC: bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mig_7series_0_0 || ORIG_REF_NAME==system_mig_7series_0_0}]

# XDC: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc_debug.xdc

# XDC: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc.xdc

# XDC: bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_dlmb_v10_1 || ORIG_REF_NAME==system_dlmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_dlmb_v10_1/system_dlmb_v10_1_ooc.xdc

# XDC: bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ilmb_v10_1 || ORIG_REF_NAME==system_ilmb_v10_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_ilmb_v10_1/system_ilmb_v10_1_ooc.xdc

# XDC: bd/system/ip/system_dlmb_bram_if_cntlr_1/system_dlmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/system/ip/system_ilmb_bram_if_cntlr_1/system_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/system/ip/system_lmb_bram_1/system_lmb_bram_1_ooc.xdc

# XDC: bd/system/ip/system_mdm_1_1/system_mdm_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_mdm_1_1 || ORIG_REF_NAME==system_mdm_1_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_mdm_1_1/system_mdm_1_1_ooc_trace.xdc

# XDC: bd/system/ip/system_rst_mig_7series_0_83M_1/system_rst_mig_7series_0_83M_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_mig_7series_0_83M_1 || ORIG_REF_NAME==system_rst_mig_7series_0_83M_1}]

# XDC: bd/system/ip/system_rst_mig_7series_0_83M_1/system_rst_mig_7series_0_83M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_mig_7series_0_83M_1 || ORIG_REF_NAME==system_rst_mig_7series_0_83M_1}]

# XDC: bd/system/ip/system_rst_mig_7series_0_83M_1/system_rst_mig_7series_0_83M_1_ooc.xdc

# XDC: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_0_0 || ORIG_REF_NAME==system_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_0_0 || ORIG_REF_NAME==system_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_0_0 || ORIG_REF_NAME==system_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_0_0 || ORIG_REF_NAME==system_axi_iic_0_0}]

# XDC: bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_2_0/system_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_0 || ORIG_REF_NAME==system_axi_gpio_3_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0_ooc.xdc

# XDC: bd/system/ip/system_axi_gpio_3_0/system_axi_gpio_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_0 || ORIG_REF_NAME==system_axi_gpio_3_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_quad_spi_1_0/system_axi_quad_spi_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_1_0 || ORIG_REF_NAME==system_axi_quad_spi_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_quad_spi_1_0/system_axi_quad_spi_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_1_0 || ORIG_REF_NAME==system_axi_quad_spi_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_quad_spi_1_0/system_axi_quad_spi_1_0_ooc.xdc

# XDC: bd/system/ip/system_axi_quad_spi_1_0/system_axi_quad_spi_1_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_1_0 || ORIG_REF_NAME==system_axi_quad_spi_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_0_0/system_PmodACL_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_PmodACL_0_0 || ORIG_REF_NAME==system_PmodACL_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_pmod_bridge_0_0/PmodACL_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_pmod_bridge_0_0 || ORIG_REF_NAME==PmodACL_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodACL_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodACL_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodACL_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_axi_gpio_0_0/PmodACL_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_gpio_0_0 || ORIG_REF_NAME==PmodACL_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_axi_gpio_0_0/PmodACL_axi_gpio_0_0_ooc.xdc

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_axi_gpio_0_0/PmodACL_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_gpio_0_0 || ORIG_REF_NAME==PmodACL_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_0_0/src/PmodACL_ooc.xdc

# XDC: bd/system/ip/system_PmodGPS_0_0/system_PmodGPS_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_PmodGPS_0_0 || ORIG_REF_NAME==system_PmodGPS_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_axi_uartlite_0_0/PmodGPS_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_uartlite_0_0 || ORIG_REF_NAME==PmodGPS_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_axi_uartlite_0_0/PmodGPS_axi_uartlite_0_0_ooc.xdc

# XDC: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_axi_uartlite_0_0/PmodGPS_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_uartlite_0_0 || ORIG_REF_NAME==PmodGPS_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_pmod_bridge_0_0/PmodGPS_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_pmod_bridge_0_0 || ORIG_REF_NAME==PmodGPS_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPS_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0_ooc.xdc

# XDC: bd/system/ip/system_PmodGPS_0_0/ip/PmodGPS_axi_gpio_0_0/PmodGPS_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodGPS_axi_gpio_0_0 || ORIG_REF_NAME==PmodGPS_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodGPS_0_0/src/PmodGPS_ooc.xdc

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/system_PmodOLEDrgb_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_PmodOLEDrgb_0_0 || ORIG_REF_NAME==system_PmodOLEDrgb_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodOLEDrgb_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_ooc.xdc

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_axi_gpio_0_1 || ORIG_REF_NAME==PmodOLEDrgb_axi_gpio_0_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodOLEDrgb_pmod_bridge_0_0 || ORIG_REF_NAME==PmodOLEDrgb_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: bd/system/ip/system_PmodACL_1_0/system_PmodACL_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_PmodACL_1_0 || ORIG_REF_NAME==system_PmodACL_1_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_pmod_bridge_0_0/PmodACL_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_pmod_bridge_0_0 || ORIG_REF_NAME==PmodACL_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodACL_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodACL_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_axi_quad_spi_0_0/PmodACL_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodACL_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_axi_gpio_0_0/PmodACL_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_gpio_0_0 || ORIG_REF_NAME==PmodACL_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_axi_gpio_0_0/PmodACL_axi_gpio_0_0_ooc.xdc

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_axi_gpio_0_0/PmodACL_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodACL_axi_gpio_0_0 || ORIG_REF_NAME==PmodACL_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_PmodACL_1_0/src/PmodACL_ooc.xdc

# XDC: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0}]

# XDC: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_ooc.xdc

# XDC: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0_0 || ORIG_REF_NAME==system_axi_intc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0_0 || ORIG_REF_NAME==system_axi_intc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_5/system_xbar_5_ooc.xdc

# XDC: bd/system/ip/system_xbar_6/system_xbar_6_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0_ooc.xdc

# XDC: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc

# XDC: bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_ooc.xdc

# XDC: bd/system/ip/system_auto_us_1/system_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/system/system_ooc.xdc
